In [1]:
import numpy as np

In [2]:
with open('data/src/sample.csv') as f:
    print(f.read())

11,12,13,14
21,22,23,24
31,32,33,34


In [3]:
a = np.loadtxt('data/src/sample.csv', delimiter=',')

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a)

[[11. 12. 13. 14.]
 [21. 22. 23. 24.]
 [31. 32. 33. 34.]]


In [6]:
print(a[1:, :2])

[[21. 22.]
 [31. 32.]]


In [7]:
print(a.mean())

22.5


In [8]:
print(a.sum(axis=0))

[63. 66. 69. 72.]
