In [1]:
import math
import numpy as np

In [2]:
print(1e1000)

inf


In [3]:
print(1e100)

1e+100


In [4]:
print(1e1000 == float('inf'))

True


In [5]:
print(1e100 == float('inf'))

False


In [6]:
print(float('inf') == math.inf == np.inf)

True


In [7]:
print(1e1000 == math.inf)

True


In [8]:
print(1e100 == math.inf)

False


In [9]:
print(float('inf') == float('inf') * 100)

True


In [10]:
print(math.isinf(1e1000))

True


In [11]:
print(math.isinf(1e100))

False


In [12]:
print(math.isinf(-1e1000))

True


In [13]:
a = np.array([1, np.inf, -np.inf])
print(a)

[  1.  inf -inf]


In [14]:
print(np.isinf(a))

[False  True  True]


In [15]:
print(np.isposinf(a))

[False  True False]


In [16]:
print(np.isneginf(a))

[False False  True]


In [17]:
print(np.isfinite(a))

[ True False False]


In [18]:
print(np.isinf(1e1000))

True


In [19]:
print(np.nan_to_num(a))

[ 1.00000000e+000  1.79769313e+308 -1.79769313e+308]


In [20]:
print(np.nan_to_num(a, posinf=1e100, neginf=-1e100))

[ 1.e+000  1.e+100 -1.e+100]


In [21]:
np.nan_to_num(a, copy=False)
print(a)

[ 1.00000000e+000  1.79769313e+308 -1.79769313e+308]


In [22]:
import sys

In [23]:
print(sys.float_info.max)

1.7976931348623157e+308


In [24]:
print(float('inf') > sys.float_info.max)

True


In [25]:
print(-float('inf') < -sys.float_info.max)

True


In [26]:
print(float('nan'))

nan


In [27]:
print(type(float('nan')))

<class 'float'>


In [28]:
print(float('inf') > float('nan'))

False


In [29]:
print(float('inf') < float('nan'))

False


In [30]:
print(float('inf') == float('nan'))

False


In [31]:
print(float('inf') > 100)

True


In [32]:
large_int = int(sys.float_info.max) * 10

In [33]:
print(large_int)

1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229481658085593321233482747978262041447231687381771809192998812504040261841248583680


In [34]:
print(type(large_int))

<class 'int'>


In [35]:
print(large_int > sys.float_info.max)

True


In [36]:
print(float('inf') > large_int)

True


In [37]:
print(float(10**308))

1e+308


In [38]:
# print(float(10**309))
# OverflowError: int too large to convert to float