In [1]:
import numpy as np

In [2]:
a = np.array([0.123456789, 0.987654321])

In [3]:
a

array([0.12345679, 0.98765432])

In [4]:
%precision 3

'%.3f'

In [5]:
a

array([0.123, 0.988])

In [6]:
print(a)

[0.123 0.988]


In [7]:
print(np.get_printoptions()['precision'])

3


In [8]:
np.set_printoptions(precision=5)

In [9]:
a

array([0.12346, 0.98765])

In [10]:
print(a)

[0.12346 0.98765]


In [11]:
print(a[0])

0.123456789


In [12]:
%precision

'%r'

In [13]:
a

array([0.12345679, 0.98765432])

In [14]:
print(np.get_printoptions()['precision'])

8


In [15]:
%precision %.2e

'%.2e'

In [16]:
a

array([0.12345679, 0.98765432])

In [17]:
np.set_printoptions(formatter={'float': '{:.2e}'.format})

In [18]:
a

array([1.23e-01, 9.88e-01])