In [1]:
import pprint

In [2]:
l_2d = [[20, 3, 100], [1, 200, 30], [300, 10, 2]]
pprint.pprint(l_2d, width=20)

[[20, 3, 100],
 [1, 200, 30],
 [300, 10, 2]]


In [3]:
pprint.pprint(sorted(l_2d), width=20)

[[1, 200, 30],
 [20, 3, 100],
 [300, 10, 2]]


In [4]:
pprint.pprint([sorted(l) for l in l_2d], width=20)

[[3, 20, 100],
 [1, 30, 200],
 [2, 10, 300]]


In [5]:
pprint.pprint([list(x) for x in zip(*[sorted(l) for l in zip(*l_2d)])], width=20)

[[1, 3, 2],
 [20, 10, 30],
 [300, 200, 100]]


In [6]:
import numpy as np

In [7]:
print(np.sort(l_2d))

[[  3  20 100]
 [  1  30 200]
 [  2  10 300]]


In [8]:
print(np.sort(l_2d, axis=0))

[[  1   3   2]
 [ 20  10  30]
 [300 200 100]]


In [9]:
print(type(np.sort(l_2d)))

<class 'numpy.ndarray'>


In [10]:
print(np.sort(l_2d).tolist())

[[3, 20, 100], [1, 30, 200], [2, 10, 300]]


In [11]:
print(type(np.sort(l_2d).tolist()))

<class 'list'>


In [12]:
l_2d_error = [[1, 2], [3, 4, 5]]

In [13]:
# print(np.sort(l_2d_error))
# ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [14]:
pprint.pprint(sorted(l_2d, key=lambda x: x[1]), width=20)

[[20, 3, 100],
 [300, 10, 2],
 [1, 200, 30]]


In [15]:
pprint.pprint(sorted(l_2d, key=lambda x: x[2]), width=20)

[[300, 10, 2],
 [1, 200, 30],
 [20, 3, 100]]


In [16]:
import operator

In [17]:
pprint.pprint(sorted(l_2d, key=operator.itemgetter(1)), width=20)

[[20, 3, 100],
 [300, 10, 2],
 [1, 200, 30]]


In [18]:
pprint.pprint(sorted(l_2d, key=operator.itemgetter(2)), width=20)

[[300, 10, 2],
 [1, 200, 30],
 [20, 3, 100]]


In [19]:
l_2d_dup = [[1, 3, 100], [1, 200, 30], [1, 3, 2]]
pprint.pprint(l_2d_dup, width=20)

[[1, 3, 100],
 [1, 200, 30],
 [1, 3, 2]]


In [20]:
pprint.pprint(sorted(l_2d_dup), width=20)

[[1, 3, 2],
 [1, 3, 100],
 [1, 200, 30]]


In [21]:
pprint.pprint(sorted(l_2d_dup, key=operator.itemgetter(0, 2)), width=20)

[[1, 3, 2],
 [1, 200, 30],
 [1, 3, 100]]


In [22]:
pprint.pprint(sorted(l_2d_dup, key=lambda x: (x[0], x[2])), width=20)

[[1, 3, 2],
 [1, 200, 30],
 [1, 3, 100]]


In [23]:
import pandas as pd

In [24]:
df = pd.DataFrame(l_2d_dup, columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
print(df)

   A    B    C
X  1    3  100
Y  1  200   30
Z  1    3    2


In [25]:
print(df.sort_values('C'))

   A    B    C
Z  1    3    2
Y  1  200   30
X  1    3  100


In [26]:
print(df.sort_values('Z', axis=1))

   A    C    B
X  1  100    3
Y  1   30  200
Z  1    2    3


In [27]:
print(df.sort_values(['A', 'C']))

   A    B    C
Z  1    3    2
Y  1  200   30
X  1    3  100


In [28]:
df = pd.DataFrame(l_2d_dup)
print(df)

   0    1    2
0  1    3  100
1  1  200   30
2  1    3    2


In [29]:
print(df.sort_values(2))

   0    1    2
2  1    3    2
1  1  200   30
0  1    3  100


In [30]:
print(df.sort_values(2, axis=1))

   0    2    1
0  1  100    3
1  1   30  200
2  1    2    3


In [31]:
print(df.sort_values([0, 2]))

   0    1    2
2  1    3    2
1  1  200   30
0  1    3  100
