In [1]:
l = [-2, -1, 0]
print(map(abs, l))

In [2]:
print(type(map(abs, l)))

<class 'map'>


In [3]:
for i in map(abs, l):
    print(i)

2
1
0


In [4]:
for i in l:
    print(abs(i))

2
1
0


In [5]:
print(list(map(abs, l)))

[2, 1, 0]


In [6]:
l_s = ['apple', 'orange', 'strawberry']
print(list(map(len, l_s)))

[5, 6, 10]


In [7]:
print(list(map(abs, range(-2, 1))))

[2, 1, 0]


In [8]:
l = [-2, -1, 0]
print(list(map(lambda x: x**2, l)))

[4, 1, 0]


In [9]:
def square(x):
    return x**2

In [10]:
print(list(map(square, l)))

[4, 1, 0]


In [11]:
l_1 = [1, 2, 3]
l_2 = [10, 20, 30]
print(list(map(lambda x, y: x * y, l_1, l_2)))

[10, 40, 90]


In [12]:
# print(list(map(abs, l_1, l_2)))
# TypeError: abs() takes exactly one argument (2 given)

In [13]:
l_3 = [100, 200, 300, 400]
print(list(map(lambda x, y, z: x * y * z, l_1, l_2, l_3)))

[1000, 8000, 27000]


In [14]:
l = [-2, -1, 0]
print([abs(x) for x in l])

[2, 1, 0]


In [15]:
print([x**2 for x in l])

[4, 1, 0]


In [16]:
l_1 = [1, 2, 3]
l_2 = [10, 20, 30]
print([x * y for x, y in zip(l_1, l_2)])

[10, 40, 90]


In [17]:
import numpy as np

In [18]:
a = np.array([-2, -1, 0])
print(np.abs(a))

[2 1 0]


In [19]:
print(a**2)

[4 1 0]


In [20]:
a_1 = np.array([1, 2, 3])
a_2 = np.array([10, 20, 30])
print(a_1 * a_2)

[10 40 90]
