In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
print(np.zeros(3))

[0. 0. 0.]


In [4]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.zeros(3).dtype)

float64


In [6]:
print(np.zeros(3, dtype=np.int64))

[0 0 0]


In [7]:
print(np.zeros(3, dtype=np.int64).dtype)

int64


In [8]:
print(np.ones(3))

[1. 1. 1.]


In [9]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.ones(3).dtype)

float64


In [11]:
print(np.ones(3, dtype=np.int64))

[1 1 1]


In [12]:
print(np.ones(3, dtype=np.int64).dtype)

int64


In [13]:
print(np.full(3, 100))

[100 100 100]


In [14]:
print(np.full((2, 3), 0.123))

[[0.123 0.123 0.123]
 [0.123 0.123 0.123]]


In [15]:
print(np.full(3, 100).dtype)

int64


In [16]:
print(np.full(3, 100.0).dtype)

float64


In [17]:
print(np.full(3, 0.123).dtype)

float64


In [18]:
print(np.full(3, 100, dtype=np.float64))

[100. 100. 100.]


In [19]:
print(np.full(3, 0.123, dtype=np.int64))

[0 0 0]
