In [1]:
import numpy as np

In [2]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
print(a.reshape(2, 3))

[[0 1 2]
 [3 4 5]]


In [4]:
print(a.reshape(-1, 3))

[[0 1 2]
 [3 4 5]]


In [5]:
print(a.reshape(2, -1))

[[0 1 2]
 [3 4 5]]


In [6]:
# print(a.reshape(3, 4))
# ValueError: cannot reshape array of size 6 into shape (3,4)

In [7]:
# print(a.reshape(-1, 4))
# ValueError: cannot reshape array of size 6 into shape (4)

In [8]:
l = [0, 1, 2, 3, 4, 5]

In [9]:
print(np.array(l).reshape(-1, 3).tolist())

[[0, 1, 2], [3, 4, 5]]


In [10]:
print(np.array(l).reshape(3, -1).tolist())

[[0, 1], [2, 3], [4, 5]]
