In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.array([12.3, 45.6, 78.9])

In [4]:
print(np.rint(a))

[12. 46. 79.]


In [5]:
l = [12.3, 45.6, 78.9]

In [6]:
print(np.rint(l))

[12. 46. 79.]


In [7]:
print(np.rint(12.3))

12.0


In [8]:
print(np.rint(a).dtype)

float64


In [9]:
print(np.rint([-3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5]))

[-4. -2. -2. -0.  0.  2.  2.  4.]
