In [1]:
import numpy as np

In [2]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [3]:
np.save('data/temp/np_save', a)

In [4]:
print(type(np.load('data/temp/np_save.npy')))

<class 'numpy.ndarray'>


In [5]:
print(np.load('data/temp/np_save.npy'))

[0 1 2 3 4]


In [6]:
np.save('data/temp/np_save', a.astype('float32'))

In [7]:
b = np.load('data/temp/np_save.npy')

In [8]:
print(b)

[0. 1. 2. 3. 4.]


In [9]:
print(b.dtype)

float32
