In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.array([12.3, 45.6, 78.9])

In [4]:
print(np.round(a))

[12. 46. 79.]


In [5]:
print(np.round(a).dtype)

float64


In [6]:
print(np.round(a).astype(int))

[12 46 79]


In [7]:
print(a.astype(int))

[12 45 78]


In [8]:
l = [12.3, 45.6, 78.9]

In [9]:
print(np.round(l))

[12. 46. 79.]


In [10]:
print(type(np.round(l)))

<class 'numpy.ndarray'>


In [11]:
print(np.round(12.3))

12.0


In [12]:
print(np.round(123.456))

123.0


In [13]:
print(np.round(123.456, 2))

123.46


In [14]:
print(np.round(123.456, -2))

100.0


In [15]:
print(np.round(123456))

123456


In [16]:
print(np.round(123456, 2))

123456


In [17]:
print(np.round(123456, -2))

123500


In [18]:
a = np.array([12345, 67890])

In [19]:
print(np.round(a, -3))

[12000 68000]


In [20]:
print(np.round(a, -3).dtype)

int64


In [21]:
print(np.round([-3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5]))

[-4. -2. -2. -0.  0.  2.  2.  4.]


In [22]:
print(np.round([-350, -250, -150, -50, 50, 150, 250, 350], -2))

[-400 -200 -200    0    0  200  200  400]


In [23]:
print(np.round([2.49, 2.5, 2.51]))

[2. 2. 3.]


In [24]:
print(np.round([249, 250, 251], -2))

[200 200 300]


In [25]:
print(np.round(0.15, 1))

0.2


In [26]:
print(round(0.15, 1))

0.1


In [27]:
print(f'{0.15:.20}')

0.14999999999999999445


In [28]:
print(np.round(56294995342131.5, 3))

56294995342131.51


In [29]:
print(round(56294995342131.5, 3))

56294995342131.5


In [30]:
a = np.array([12.3, 45.6, 78.9])

In [31]:
print(np.around(a))

[12. 46. 79.]


In [32]:
print(np.around(a, -1))

[10. 50. 80.]


In [33]:
print(a.round())

[12. 46. 79.]


In [34]:
print(a.round(-1))

[10. 50. 80.]


In [35]:
def my_round(x, decimals=0):
    return np.floor(x * 10**decimals + 0.5) / 10**decimals

In [36]:
a = np.array([-3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5])

In [37]:
print(np.round(a))

[-4. -2. -2. -0.  0.  2.  2.  4.]


In [38]:
print(my_round(a))

[-3. -2. -1.  0.  1.  2.  3.  4.]


In [39]:
print(a / 10)

[-0.35 -0.25 -0.15 -0.05  0.05  0.15  0.25  0.35]


In [40]:
print(np.round(a / 10, 1))

[-0.4 -0.2 -0.2 -0.   0.   0.2  0.2  0.4]


In [41]:
print(my_round(a / 10, 1))

[-0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4]


In [42]:
def my_round2(x, decimals=0):
    return np.sign(x) * np.floor(np.abs(x) * 10**decimals + 0.5) / 10**decimals

In [43]:
print(a)

[-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]


In [44]:
print(my_round(a))

[-3. -2. -1.  0.  1.  2.  3.  4.]


In [45]:
print(my_round2(a))

[-4. -3. -2. -1.  1.  2.  3.  4.]


In [46]:
print(a / 10)

[-0.35 -0.25 -0.15 -0.05  0.05  0.15  0.25  0.35]


In [47]:
print(my_round(a / 10, 1))

[-0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4]


In [48]:
print(my_round2(a / 10, 1))

[-0.4 -0.3 -0.2 -0.1  0.1  0.2  0.3  0.4]
