In [1]:
import numpy as np
import pandas as pd

In [2]:
print(np.__version__)

1.26.2


In [3]:
print(pd.__version__)

2.1.4


In [4]:
a_2d = np.array([[1, 2], [3, 4]])
print(a_2d)

[[1 2]
 [3 4]]


In [5]:
print(pd.DataFrame(a_2d))

   0  1
0  1  2
1  3  4


In [6]:
a_1d = np.array([1, 2])
print(a_1d)

[1 2]


In [7]:
print(pd.DataFrame(a_1d))

   0
0  1
1  2


In [8]:
a_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# print(pd.DataFrame(a_3d))
# ValueError: Must pass 2-d input. shape=(2, 2, 2)

In [10]:
print(pd.DataFrame(data=a_2d, index=['X', 'Y'], columns=['A', 'B'], dtype=float))

     A    B
X  1.0  2.0
Y  3.0  4.0


In [11]:
a = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(a)

In [12]:
print(np.shares_memory(a, df))

True


In [13]:
a[0, 0] = 100
print(a)

[[100   2]
 [  3   4]]


In [14]:
print(df)

     0  1
0  100  2
1    3  4


In [15]:
a = np.array([[1, 2], [3, 4]])
df_copy = pd.DataFrame(a, copy=True)

In [16]:
print(np.shares_memory(a, df_copy))

False


In [17]:
a[0, 0] = 100
print(a)

[[100   2]
 [  3   4]]


In [18]:
print(df_copy)

   0  1
0  1  2
1  3  4


In [19]:
a = np.array([[1, 2], [3, 4]])
df_float = pd.DataFrame(a, dtype=float)

In [20]:
print(np.shares_memory(a, df_float))

False


In [21]:
a_1d = np.array([1, 2])
print(a_1d)

[1 2]


In [22]:
print(pd.Series(a_1d))

0    1
1    2
dtype: int64


In [23]:
a_2d = np.array([[1, 2], [3, 4]])
print(a_2d)

[[1 2]
 [3 4]]


In [24]:
# print(pd.Series(a_2d))
# ValueError: Data must be 1-dimensional, got ndarray of shape (2, 2) instead

In [25]:
print(pd.Series(a_1d, index=['A', 'B'], name='my_series', dtype=float))

A    1.0
B    2.0
Name: my_series, dtype: float64


In [26]:
a = np.array([1, 2])
print(np.shares_memory(a, pd.Series(a)))

True


In [27]:
print(np.shares_memory(a, pd.Series(a, copy=True)))

False


In [28]:
print(np.shares_memory(a, pd.Series(a, dtype=float)))

False
