In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape((3, 3))

In [3]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print(a.diagonal())

[0 4 8]


In [5]:
print(a.diagonal(offset=1))

[1 5]


In [6]:
print(a.diagonal(offset=3))

[]


In [7]:
print(a.diagonal(offset=-2))

[6]


In [8]:
a = np.arange(12).reshape((3, 4))

In [9]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(a.diagonal())

[ 0  5 10]


In [11]:
print(a.diagonal(offset=1))

[ 1  6 11]


In [12]:
a = np.arange(3)

In [13]:
print(a)

[0 1 2]


In [14]:
# a.diagonal()
# ValueError: diag requires an array of at least two dimensions