In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print(np.sum(a, axis=0))

[12 15 18 21]


In [5]:
print(np.sum(a, axis=1))

[ 6 22 38]


In [6]:
print(np.sum(a))

66


In [7]:
print(np.sum(a, axis=None))

66


In [8]:
# print(np.sum(a, axis=2))
# AxisError: axis 2 is out of bounds for array of dimension 2

In [9]:
print(np.sum(a, axis=-1))

[ 6 22 38]


In [10]:
print(np.sum(a, axis=-2))

[12 15 18 21]


In [11]:
# print(np.sum(a, axis=-3))
# AxisError: axis -3 is out of bounds for array of dimension 2

In [12]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [13]:
print(np.sum(a, axis=0))

[3 5 7]


In [14]:
print(np.sum(a, axis=1))

[ 3 12]


In [15]:
print(a[0, :] + a[1, :])

[3 5 7]


In [16]:
print(a[:, 0] + a[:, 1] + a[:, 2])

[ 3 12]


In [17]:
a = np.stack([np.ones((3, 4), int), np.full((3, 4), 10)])
print(a)

[[[ 1  1  1  1]
  [ 1  1  1  1]
  [ 1  1  1  1]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


In [18]:
print(a.shape)

(2, 3, 4)


In [19]:
print(np.sum(a, axis=0))

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]


In [20]:
print(np.sum(a, axis=1))

[[ 3  3  3  3]
 [30 30 30 30]]


In [21]:
print(np.sum(a, axis=2))

[[ 4  4  4]
 [40 40 40]]


In [22]:
print(a[0, :, :] + a[1, :, :])

[[11 11 11 11]
 [11 11 11 11]
 [11 11 11 11]]


In [23]:
print(a[:, 0, :] + a[:, 1, :] + a[:, 2, :])

[[ 3  3  3  3]
 [30 30 30 30]]


In [24]:
print(a[:, :, 0] + a[:, :, 1] + a[:, :, 2] + a[:, :, 3])

[[ 4  4  4]
 [40 40 40]]


In [25]:
print(np.sum(a, axis=(0, 1)))

[33 33 33 33]


In [26]:
print(np.sum(a, axis=(0, 2)))

[44 44 44]


In [27]:
print(np.sum(a, axis=(1, 2)))

[ 12 120]


In [28]:
print(
    a[0, 0, :] + a[0, 1, :] + a[0, 2, :] +
    a[1, 0, :] + a[1, 1, :] + a[1, 2, :]
)

[33 33 33 33]


In [29]:
print(
    a[0, :, 0] + a[0, :, 1] + a[0, :, 2] + a[0, :, 3] +
    a[1, :, 0] + a[1, :, 1] + a[1, :, 2] + a[1, :, 3]
)

[44 44 44]


In [30]:
print(
    a[:, 0, 0] + a[:, 0, 1] + a[:, 0, 2] + a[:, 0, 3] + 
    a[:, 1, 0] + a[:, 1, 1] + a[:, 1, 2] + a[:, 1, 3] + 
    a[:, 2, 0] + a[:, 2, 1] + a[:, 2, 2] + a[:, 2, 3]
)

[ 12 120]
