In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.array([1, 2, 3])
print(a)
print(a.dtype)

[1 2 3]
int64


In [4]:
a_float = a.astype(np.float32)
print(a_float)
print(a_float.dtype)

[1. 2. 3.]
float32


In [5]:
print(a)
print(a.dtype)

[1 2 3]
int64


In [6]:
a_int = a.astype('int32')
print(a_int)
print(a_int.dtype)

[1 2 3]
int32


In [7]:
a_uint = a.astype('u8')
print(a_uint)
print(a_uint.dtype)

[1 2 3]
uint64


In [8]:
a_float = a.astype(float)
print(a_float)
print(a_float.dtype)

[1. 2. 3.]
float64


In [9]:
a = np.array([-2, -1.5, -1, -0.5, 0.5, 1, 1.5, 2])

In [10]:
print(a.astype(int))

[-2 -1 -1  0  0  1  1  2]
