In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
print(a < 4)

[[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [4]:
print(a % 2 == 1)

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]


In [5]:
print(np.sum(a < 4))

4


In [6]:
print(np.sum(a % 2 == 1))

6


In [7]:
print((a < 4).sum())

4


In [8]:
print((a % 2 == 1).sum())

6


In [9]:
print(np.sum(a < 4, axis=0))

[1 1 1 1]


In [10]:
print(np.sum(a < 4, axis=1))

[4 0 0]


In [11]:
print(np.sum(a % 2 == 1, axis=0))

[0 3 0 3]


In [12]:
print(np.sum(a % 2 == 1, axis=1))

[2 2 2]


In [13]:
print(np.any(a < 4))

True


In [14]:
print(np.any(a > 100))

False


In [15]:
print(np.any(a < 4, axis=0))

[ True  True  True  True]


In [16]:
print(np.any(a < 4, axis=1))

[ True False False]


In [17]:
print(np.all(a < 4))

False


In [18]:
print(np.all(a < 100))

True


In [19]:
print(np.all(a < 4, axis=0))

[False False False False]


In [20]:
print(np.all(a < 4, axis=1))

[ True False False]


In [21]:
print((a < 4) | (a % 2 == 1))

[[ True  True  True  True]
 [False  True False  True]
 [False  True False  True]]


In [22]:
print(np.sum((a < 4) | (a % 2 == 1)))

8


In [23]:
print(np.sum((a < 4) | (a % 2 == 1), axis=0))

[1 3 1 3]


In [24]:
print(np.sum((a < 4) | (a % 2 == 1), axis=1))

[4 2 2]


In [25]:
print(((a < 4) | (a % 2 == 1)).sum())

8


In [26]:
print(((a < 4) | (a % 2 == 1)).sum(axis=0))

[1 3 1 3]


In [27]:
print(((a < 4) | (a % 2 == 1)).sum(axis=1))

[4 2 2]
