In [1]:
import numpy as np

In [2]:
arr = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(arr)

[[ 11.  12.  nan  14.]
 [ 21.  nan  nan  24.]
 [ 31.  32.  33.  34.]]


In [3]:
print(np.isnan(arr))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [4]:
print(arr[~np.isnan(arr)])

[ 11.  12.  14.  21.  24.  31.  32.  33.  34.]


In [5]:
print(np.isnan(arr).any(axis=1))

[ True  True False]


In [6]:
print(~np.isnan(arr).any(axis=1))

[False False  True]


In [7]:
print(arr[~np.isnan(arr).any(axis=1), :])

[[ 31.  32.  33.  34.]]


In [8]:
print(arr[~np.isnan(arr).any(axis=1)])

[[ 31.  32.  33.  34.]]


In [9]:
print(~np.isnan(arr).any(axis=0))

[ True False False  True]


In [10]:
print(arr[:, ~np.isnan(arr).any(axis=0)])

[[ 11.  14.]
 [ 21.  24.]
 [ 31.  34.]]
