In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


In [4]:
print(np.isnan(a))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [5]:
print(~np.isnan(a))

[[ True  True False  True]
 [ True False False  True]
 [ True  True  True  True]]


In [6]:
print(a[~np.isnan(a)])

[11. 12. 14. 21. 24. 31. 32. 33. 34.]


In [7]:
print(np.isnan(a).any(axis=1))

[ True  True False]


In [8]:
print(~np.isnan(a).any(axis=1))

[False False  True]


In [9]:
print(a[~np.isnan(a).any(axis=1), :])

[[31. 32. 33. 34.]]


In [10]:
print(a[~np.isnan(a).any(axis=1)])

[[31. 32. 33. 34.]]


In [11]:
a[1, 0] = np.nan
a[1, 3] = np.nan
print(a)

[[11. 12. nan 14.]
 [nan nan nan nan]
 [31. 32. 33. 34.]]


In [12]:
print(np.isnan(a).all(axis=1))

[False  True False]


In [13]:
print(~np.isnan(a).all(axis=1))

[ True False  True]


In [14]:
print(a[~np.isnan(a).all(axis=1)])

[[11. 12. nan 14.]
 [31. 32. 33. 34.]]


In [15]:
a = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


In [16]:
print(np.isnan(a))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [17]:
print(np.isnan(a).any(axis=0))

[False  True  True False]


In [18]:
print(~np.isnan(a).any(axis=0))

[ True False False  True]


In [19]:
print(a[:, ~np.isnan(a).any(axis=0)])

[[11. 14.]
 [21. 24.]
 [31. 34.]]


In [20]:
a[2, 2] = np.nan
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. nan 34.]]


In [21]:
print(np.isnan(a).all(axis=0))

[False False  True False]


In [22]:
print(~np.isnan(a).all(axis=0))

[ True  True False  True]


In [23]:
print(a[:, ~np.isnan(a).all(axis=0)])

[[11. 12. 14.]
 [21. nan 24.]
 [31. 32. 34.]]
