In [1]:
import numpy as np

In [2]:
arr = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(arr)

[[ 11.  12.  nan  14.]
 [ 21.  nan  nan  24.]
 [ 31.  32.  33.  34.]]


In [3]:
print(arr.sum())

nan


In [4]:
print(np.sum(arr))

nan


In [5]:
print(np.nansum(arr))

212.0


In [6]:
print(np.nansum(arr, axis=0))

[ 63.  44.  33.  72.]


In [7]:
print(np.nansum(arr, axis=1))

[  37.   45.  130.]


In [8]:
print(np.nanmean(arr))

23.5555555556


In [9]:
print(np.nanmax(arr))

34.0


In [10]:
print(np.nanmin(arr))

11.0


In [11]:
print(np.nanstd(arr))

8.90831211237


In [12]:
print(np.nanvar(arr))

79.3580246914
