In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
rng = np.random.default_rng()

In [4]:
print(rng.standard_normal())

0.08496250507973527


In [5]:
print(rng.standard_normal(3))

[ 1.21769711  1.81125807 -0.87641522]


In [6]:
print(rng.standard_normal((2, 3)))

[[-1.79057437  0.30921794  0.78466028]
 [ 0.9669326  -0.23709503  0.17453728]]


In [7]:
print(np.random.standard_normal((2, 3)))

[[ 1.59966341 -2.3255136  -0.90314338]
 [-0.90576614  0.45550908 -0.88593054]]


In [8]:
print(np.random.randn(2, 3))

[[ 0.13158995 -0.34018141  0.26866075]
 [-0.35383739 -1.85442183 -0.1316313 ]]


In [9]:
rng = np.random.default_rng()

In [10]:
print(rng.normal(2, 2.5))

1.4099095964428612


In [11]:
print(rng.normal(2, 2.5, 3))

[-1.02713245  2.80603029  6.84660003]


In [12]:
print(rng.normal(2, 2.5, (2, 3)))

[[ 4.23662681  2.36596096 -0.08259898]
 [ 2.27105608  1.58751381 -2.42582859]]


In [13]:
print(np.random.normal(2, 2.5, (2, 3)))

[[ 4.43180284  3.74464437  0.79083482]
 [-0.3631814   0.39375677  7.8085918 ]]
