In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])

In [3]:
print(np.tile(a, 2))

[0 1 2 3 0 1 2 3]


In [4]:
print(np.tile(a, (3, 2)))

[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]


In [5]:
print(np.tile(a, (2, 1)))

[[0 1 2 3]
 [0 1 2 3]]


In [6]:
a = np.array([[11, 12], [21, 22]])

In [7]:
print(np.tile(a, 2))

[[11 12 11 12]
 [21 22 21 22]]


In [8]:
print(np.tile(a, (3, 2)))

[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]


In [9]:
print(np.tile(a, (2, 1)))

[[11 12]
 [21 22]
 [11 12]
 [21 22]]
