In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


In [4]:
print(rng.random())

0.9124223789440322


In [5]:
print(type(rng.random()))

<class 'float'>


In [6]:
print(rng.random(3))

[0.89316041 0.63122969 0.05225701]


In [7]:
print(type(rng.random(3)))

<class 'numpy.ndarray'>


In [8]:
print(rng.random((2, 3)))

[[0.06036965 0.56058557 0.81693522]
 [0.30997042 0.81240124 0.87474847]]


In [9]:
print(type(rng.random((2, 3))))

<class 'numpy.ndarray'>


In [10]:
rng_1 = np.random.default_rng(1234)
print(rng_1.random())

0.9766997666981422


In [11]:
rng_2 = np.random.default_rng(1234)
print(rng_2.random())

0.9766997666981422


In [12]:
rng_mt = np.random.Generator(np.random.MT19937(1234))
print(rng_mt)

Generator(MT19937)


In [13]:
print(rng_mt.random())

0.12038356302504949
