In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [4]:
a_slice = a[:, :2]
print(a_slice)

[[0 1]
 [3 4]]


In [5]:
print(np.shares_memory(a, a_slice))

True


In [6]:
a_slice[0, 0] = 100
print(a_slice)

[[100   1]
 [  3   4]]


In [7]:
print(a)

[[100   1   2]
 [  3   4   5]]


In [8]:
a[0, 0] = 0
print(a)

[[0 1 2]
 [3 4 5]]


In [9]:
print(a_slice)

[[0 1]
 [3 4]]


In [10]:
a_boolean_index = a[:, [True, False, True]]
print(a_boolean_index)

[[0 2]
 [3 5]]


In [11]:
print(np.shares_memory(a, a_boolean_index))

False


In [12]:
a_boolean_index[0, 0] = 100
print(a_boolean_index)

[[100   2]
 [  3   5]]


In [13]:
print(a)

[[0 1 2]
 [3 4 5]]


In [14]:
a_slice_copy = a[:, :2].copy()
print(a_slice_copy)

[[0 1]
 [3 4]]


In [15]:
print(np.shares_memory(a, a_slice_copy))

False


In [16]:
a_slice_copy[0, 0] = 100
print(a_slice_copy)

[[100   1]
 [  3   4]]


In [17]:
print(a)

[[0 1 2]
 [3 4 5]]


In [18]:
a_boolean_index_view = a[:, [True, False, True]].view()
print(a_boolean_index_view)

[[0 2]
 [3 5]]


In [19]:
print(np.shares_memory(a, a_boolean_index_view))

False


In [20]:
a_boolean_index_view[0, 0] = 100
print(a_boolean_index_view)

[[100   2]
 [  3   5]]


In [21]:
print(a)

[[0 1 2]
 [3 4 5]]


In [22]:
a_fancy_index_slice = a[:, [0, 2]]
print(a_fancy_index_slice)

[[0 2]
 [3 5]]


In [23]:
print(np.shares_memory(a, a_fancy_index_slice))

False


In [24]:
a_scalar_slice = a[1, :2]
print(a_scalar_slice)

[3 4]


In [25]:
print(np.shares_memory(a, a_scalar_slice))

True
