In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(a)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


In [4]:
print(np.sum(a))

nan


In [5]:
print(a.sum())

nan


In [6]:
print(np.nansum(a))

212.0


In [7]:
print(np.nansum(a, axis=0))

[63. 44. 33. 72.]


In [8]:
print(np.nansum(a, axis=1))

[ 37.  45. 130.]


In [9]:
print(np.nanmean(a))

23.555555555555557


In [10]:
print(np.nanmax(a))

34.0


In [11]:
print(np.nanmin(a))

11.0


In [12]:
print(np.nanstd(a))

8.908312112367753


In [13]:
print(np.nanvar(a))

79.35802469135803
