In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.2


In [3]:
a = np.array([[2, 5], [1, 3]])
print(a)

[[2 5]
 [1 3]]


In [4]:
print(np.linalg.inv(a))

[[ 3. -5.]
 [-1.  2.]]


In [5]:
print(a @ np.linalg.inv(a))

[[1. 0.]
 [0. 1.]]


In [6]:
a_singular = np.array([[0, 0], [1, 3]])
print(a_singular)

[[0 0]
 [1 3]]


In [7]:
# print(np.linalg.inv(a_singular))
# LinAlgError: Singular matrix

In [8]:
print(np.linalg.pinv(a_singular))

[[0.  0.1]
 [0.  0.3]]


In [9]:
print(a_singular @ np.linalg.pinv(a_singular))

[[0. 0.]
 [0. 1.]]


In [10]:
print(np.linalg.pinv(np.linalg.pinv(a_singular)))

[[0. 0.]
 [1. 3.]]


In [11]:
a = np.array([[2, 5], [1, 3]])
print(a)

[[2 5]
 [1 3]]


In [12]:
print(np.linalg.inv(a))

[[ 3. -5.]
 [-1.  2.]]


In [13]:
print(np.linalg.pinv(a))

[[ 3. -5.]
 [-1.  2.]]
