In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(16).reshape(4, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a_split = np.split(a, 2)

In [5]:
print(type(a_split))

<class 'list'>


In [6]:
print(len(a_split))

2


In [7]:
print(a_split[0])

[[0 1 2 3]
 [4 5 6 7]]


In [8]:
print(a_split[1])

[[ 8  9 10 11]
 [12 13 14 15]]


In [9]:
print(type(a_split[0]))

<class 'numpy.ndarray'>


In [10]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
a0, a1 = np.split(a, 2)

In [12]:
print(a0)

[[0 1 2 3]
 [4 5 6 7]]


In [13]:
print(a1)

[[ 8  9 10 11]
 [12 13 14 15]]


In [14]:
# np.split(a, 3)
# ValueError: array split does not result in an equal division

In [15]:
a0, a1, a2 = np.split(a, [1, 3])

In [16]:
print(a0)

[[0 1 2 3]]


In [17]:
print(a1)

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print(a2)

[[12 13 14 15]]


In [19]:
a0, a1 = np.split(a, [1])

In [20]:
print(a0)

[[0 1 2 3]]


In [21]:
print(a1)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
a0, a1 = np.split(a, [10])

In [23]:
print(a0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [24]:
print(a1)

[]


In [25]:
print(type(a1))

<class 'numpy.ndarray'>


In [26]:
a0, a1 = np.split(a, 2, 0)

In [27]:
print(a0)

[[0 1 2 3]
 [4 5 6 7]]


In [28]:
print(a1)

[[ 8  9 10 11]
 [12 13 14 15]]


In [29]:
a0, a1 = np.split(a, 2, 1)

In [30]:
print(a0)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [31]:
print(a1)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [32]:
# np.split(a, 2, 2)
# IndexError: tuple index out of range

In [33]:
a_3d = np.arange(24).reshape(2, 3, 4)
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [34]:
print(a_3d.shape)

(2, 3, 4)


In [35]:
a0, a1 = np.split(a_3d, 2, 0)

In [36]:
print(a0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [37]:
print(a1)

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [38]:
a0, a1 = np.split(a_3d, [1], 2)

In [39]:
print(a0)

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [40]:
print(a1)

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[13 14 15]
  [17 18 19]
  [21 22 23]]]
