In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.0


In [3]:
print(np.pi)

3.141592653589793


In [4]:
print(np.radians(180))

3.141592653589793


In [5]:
print(type(np.radians(180)))

<class 'numpy.float64'>


In [6]:
a = np.array([0, 90, 180])
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(np.radians(a))

[0.         1.57079633 3.14159265]


In [8]:
print(type(np.radians(a)))

<class 'numpy.ndarray'>


In [9]:
l = [0, 90, 180]
print(type(l))

<class 'list'>


In [10]:
print(np.radians(l))

[0.         1.57079633 3.14159265]


In [11]:
print(type(np.radians(l)))

<class 'numpy.ndarray'>


In [12]:
print(np.radians(a))

[0.         1.57079633 3.14159265]


In [13]:
print(np.round(np.radians(a)))

[0. 2. 3.]


In [14]:
print(np.round(np.radians(a), 2))

[0.   1.57 3.14]


In [15]:
print(np.sin(np.radians(30)))

0.49999999999999994


In [16]:
print(np.round(np.sin(np.radians(30)), 1))

0.5


In [17]:
print(np.sin(np.radians([0, 30, 90])))

[0.  0.5 1. ]


In [18]:
print(np.sin(np.radians([0, 30, 90]))[1])

0.49999999999999994


In [19]:
np.set_printoptions(precision=20)
print(np.sin(np.radians([0, 30, 90])))

[0.                  0.49999999999999994 1.                 ]


In [20]:
np.set_printoptions(precision=8)  # reset to default

In [21]:
print(np.radians([0, 90, 180]))

[0.         1.57079633 3.14159265]


In [22]:
print(np.deg2rad([0, 90, 180]))

[0.         1.57079633 3.14159265]


In [23]:
print(np.degrees([0, np.pi / 2, np.pi]))

[  0.  90. 180.]


In [24]:
print(np.rad2deg([0, np.pi / 2, np.pi]))

[  0.  90. 180.]


In [25]:
print(np.sin(np.radians([0, 30, 90])))

[0.  0.5 1. ]


In [26]:
print(np.degrees(np.arcsin([0, 0.5, 1])))

[ 0. 30. 90.]


In [27]:
print(np.cos(np.radians([0, 60, 90])))

[1.000000e+00 5.000000e-01 6.123234e-17]


In [28]:
print(np.round(np.cos(np.radians([0, 60, 90])), 1))

[1.  0.5 0. ]


In [29]:
print(np.degrees(np.arccos([0, 0.5, 1])))

[90. 60.  0.]


In [30]:
print(np.tan(np.radians([0, 45, 90])))

[0.00000000e+00 1.00000000e+00 1.63312394e+16]


In [31]:
print(np.degrees(np.arctan([0, 1, np.inf])))

[ 0. 45. 90.]


In [32]:
print(np.degrees(np.arctan([-np.inf, -1, 0, 1, np.inf])))

[-90. -45.   0.  45.  90.]


In [33]:
print(np.degrees(np.arctan2(-1, 1)))

-45.0


In [34]:
print(np.degrees(np.arctan2(1, -1)))

135.0


In [35]:
print(np.degrees(np.arctan2([0, 1, 1, 1, 0],
                            [0, 1, 0, -1, -1])))

[  0.  45.  90. 135. 180.]


In [36]:
print(np.degrees(np.arctan2([0, -1, -1, -1, 0],
                            [0, 1, 0, -1, -1])))

[   0.  -45.  -90. -135.  180.]


In [37]:
print(np.degrees(np.arctan2(0, -1)))

180.0


In [38]:
print(np.degrees(np.arctan2(-0.0, -1.0)))

-180.0


In [39]:
print(np.degrees(np.arctan2(-0, -1)))

180.0


In [40]:
print(np.degrees(np.arctan2([0.0, -0.0, 0.0, -0.0],
                            [0.0, 0.0, -0.0, -0.0])))

[   0.   -0.  180. -180.]


In [41]:
print(np.sin(-0.0))

-0.0


In [42]:
print(np.arcsin(-0.0))

-0.0


In [43]:
print(np.tan(-0.0))

-0.0


In [44]:
print(np.arctan(-0.0))

-0.0
