In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.0


In [3]:
a_1d = np.array([1, 2, 3, 4, 5, 6])
print(a_1d)

[1 2 3 4 5 6]


In [4]:
print(np.cumsum(a_1d))

[ 1  3  6 10 15 21]


In [5]:
print(np.cumsum(a_1d, dtype=float))

[ 1.  3.  6. 10. 15. 21.]


In [6]:
print(a_1d.cumsum())

[ 1  3  6 10 15 21]


In [7]:
print(a_1d.cumsum(dtype=float))

[ 1.  3.  6. 10. 15. 21.]


In [8]:
l = [1, 2, 3, 4, 5, 6]

In [9]:
print(np.cumsum(l))

[ 1  3  6 10 15 21]


In [10]:
print(type(np.cumsum(l)))

<class 'numpy.ndarray'>


In [11]:
a_2d = a_1d.reshape(2, 3)
print(a_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
print(np.cumsum(a_2d))

[ 1  3  6 10 15 21]


In [13]:
print(np.cumsum(a_2d, axis=0))

[[1 2 3]
 [5 7 9]]


In [14]:
print(np.cumsum(a_2d, axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [15]:
print(a_2d.cumsum())

[ 1  3  6 10 15 21]


In [16]:
print(a_2d.cumsum(axis=0))

[[1 2 3]
 [5 7 9]]


In [17]:
print(a_2d.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [18]:
l_2d = [[1, 2, 3], [4, 5, 6]]

In [19]:
print(np.cumsum(l_2d))

[ 1  3  6 10 15 21]


In [20]:
print(np.cumsum(l_2d, axis=0))

[[1 2 3]
 [5 7 9]]


In [21]:
print(np.cumsum(l_2d, axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [22]:
l_2d_error = [[1, 2, 3], [4, 5]]

In [23]:
print(np.cumsum(l_2d_error))

[list([1, 2, 3]) list([1, 2, 3, 4, 5])]


/usr/local/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [24]:
print(np.cumprod(a_1d))

[  1   2   6  24 120 720]


In [25]:
print(np.cumprod(a_1d, dtype=float))

[  1.   2.   6.  24. 120. 720.]


In [26]:
print(a_1d.cumprod())

[  1   2   6  24 120 720]


In [27]:
print(a_1d.cumprod(dtype=float))

[  1.   2.   6.  24. 120. 720.]


In [28]:
print(np.cumprod(a_2d))

[  1   2   6  24 120 720]


In [29]:
print(np.cumprod(a_2d, axis=0))

[[ 1  2  3]
 [ 4 10 18]]


In [30]:
print(np.cumprod(a_2d, axis=1))

[[  1   2   6]
 [  4  20 120]]


In [31]:
print(a_2d.cumprod())

[  1   2   6  24 120 720]


In [32]:
print(a_2d.cumprod(axis=0))

[[ 1  2  3]
 [ 4 10 18]]


In [33]:
print(a_2d.cumprod(axis=1))

[[  1   2   6]
 [  4  20 120]]


In [34]:
print(np.cumprod(l))

[  1   2   6  24 120 720]


In [35]:
print(np.cumprod(l_2d))

[  1   2   6  24 120 720]


In [36]:
print(np.cumprod(l_2d, axis=0))

[[ 1  2  3]
 [ 4 10 18]]


In [37]:
print(np.cumprod(l_2d, axis=1))

[[  1   2   6]
 [  4  20 120]]
