In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
print(np.where(a < 4, -1, 100))

[[ -1  -1  -1]
 [ -1 100 100]
 [100 100 100]]


In [4]:
print(np.where(a < 4, True, False))

[[ True  True  True]
 [ True False False]
 [False False False]]


In [5]:
print(a < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [6]:
print(np.where((a > 2) & (a < 6), -1, 100))

[[100 100 100]
 [ -1  -1  -1]
 [100 100 100]]


In [7]:
print(np.where((a > 2) & (a < 6) | (a == 7), -1, 100))

[[100 100 100]
 [ -1  -1  -1]
 [100  -1 100]]


In [8]:
print((a > 2) & (a < 6))

[[False False False]
 [ True  True  True]
 [False False False]]


In [9]:
print((a > 2) & (a < 6) | (a == 7))

[[False False False]
 [ True  True  True]
 [False  True False]]


In [10]:
print(np.where(a < 4, -1, a))

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [11]:
print(np.where(a < 4, a, 100))

[[  0   1   2]
 [  3 100 100]
 [100 100 100]]


In [12]:
a_org = np.arange(9).reshape((3, 3))
print(a_org)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
a_new = np.where(a_org < 4, -1, a_org)
print(a_new)

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [14]:
print(a_org)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
a_org[a_org < 4] = -1
print(a_org)

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [16]:
print(np.where(a < 4, a * 10, a))

[[ 0 10 20]
 [30  4  5]
 [ 6  7  8]]


In [17]:
print(np.where(a < 4))

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))


In [18]:
print(type(np.where(a < 4)))

<class 'tuple'>
