In [1]:
import numpy as np

In [2]:
a = np.arange(3)
print(a)

[0 1 2]


In [3]:
print(a.shape)

(3,)


In [4]:
print(np.broadcast_to(a, (3, 3)))

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [5]:
print(type(np.broadcast_to(a, (3, 3))))

<class 'numpy.ndarray'>


In [6]:
# print(np.broadcast_to(a, (2, 2)))
# ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,) and requested shape (2,2)