In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(6, dtype=np.int8).reshape(1, 2, 3)
print(a)

[[[0 1 2]
  [3 4 5]]]


In [4]:
print(a.shape)

(1, 2, 3)


In [5]:
print(a.dtype)

int8


In [6]:
np.save('data/temp/np_save', a)

In [7]:
a_load = np.load('data/temp/np_save.npy')
print(a_load)

[[[0 1 2]
  [3 4 5]]]


In [8]:
print(a_load.shape)

(1, 2, 3)


In [9]:
print(a_load.dtype)

int8


In [10]:
a1 = np.arange(5)
print(a1)

[0 1 2 3 4]


In [11]:
a2 = np.arange(5, 10)
print(a2)

[5 6 7 8 9]


In [12]:
np.savez('data/temp/np_savez', a1, a2)

In [13]:
npz = np.load('data/temp/np_savez.npz')
print(type(npz))

<class 'numpy.lib.npyio.NpzFile'>


In [14]:
print(npz.files)

['arr_0', 'arr_1']


In [15]:
print(npz['arr_0'])

[0 1 2 3 4]


In [16]:
print(npz['arr_1'])

[5 6 7 8 9]


In [17]:
np.savez('data/temp/np_savez_kw', x=a1, y=a2)

In [18]:
npz_kw = np.load('data/temp/np_savez_kw.npz')
print(npz_kw.files)

['x', 'y']


In [19]:
print(npz_kw['x'])

[0 1 2 3 4]


In [20]:
print(npz_kw['y'])

[5 6 7 8 9]


In [21]:
np.savez('data/temp/np_savez_kw2', a1, y=a2)

In [22]:
npz_kw2 = np.load('data/temp/np_savez_kw2.npz')
print(npz_kw2.files)

['y', 'arr_0']


In [23]:
print(npz_kw2['arr_0'])

[0 1 2 3 4]


In [24]:
print(npz_kw2['y'])

[5 6 7 8 9]


In [25]:
np.savez_compressed('data/temp/np_savez_comp', a1, a2)

In [26]:
npz_comp = np.load('data/temp/np_savez_comp.npz')
print(type(npz_comp))

<class 'numpy.lib.npyio.NpzFile'>


In [27]:
print(npz_comp.files)

['arr_0', 'arr_1']


In [28]:
print(npz_comp['arr_0'])

[0 1 2 3 4]


In [29]:
print(npz_comp['arr_1'])

[5 6 7 8 9]


In [30]:
np.savez_compressed('data/temp/np_savez_comp_kw', x=a1, y=a2)

In [31]:
npz_comp_kw = np.load('data/temp/np_savez_comp_kw.npz')
print(npz_comp_kw.files)

['x', 'y']


In [32]:
print(npz_comp_kw['x'])

[0 1 2 3 4]


In [33]:
print(npz_comp_kw['y'])

[5 6 7 8 9]
