In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.ones((3, 4), int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
print(a.shape)

(3, 4)


In [5]:
print(np.sum(a, axis=1))

[4 4 4]


In [6]:
print(np.sum(a, axis=1).shape)

(3,)


In [7]:
print(np.sum(a, axis=1, keepdims=True))

[[4]
 [4]
 [4]]


In [8]:
print(np.sum(a, axis=1, keepdims=True).shape)

(3, 1)


In [9]:
# print(a + np.sum(a, axis=1))
# ValueError: operands could not be broadcast together with shapes (3,4) (3,)

In [10]:
print(a + np.sum(a, axis=1, keepdims=True))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [11]:
print(a + np.sum(a, axis=0))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [12]:
print(a + np.sum(a, axis=0, keepdims=True))

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [13]:
a = np.ones((2, 3, 4), int)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [14]:
print(np.sum(a, axis=(0, 2)))

[8 8 8]


In [15]:
print(np.sum(a, axis=(0, 2), keepdims=True))

[[[8]
  [8]
  [8]]]


In [16]:
# print(a + np.sum(a, axis=(0, 2)))
# ValueError: operands could not be broadcast together with shapes (2,3,4) (3,)

In [17]:
print(a + np.sum(a, axis=(0, 2), keepdims=True))

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
