In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
b = np.arange(12).reshape(4, 3).T
print(b)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [5]:
a_compare = a < b
print(a_compare)

[[False  True  True  True]
 [False False  True  True]
 [False False False False]]


In [6]:
print(type(a_compare))

<class 'numpy.ndarray'>


In [7]:
print(a_compare.dtype)

bool


In [8]:
b_float = b.astype(float)
print(b_float)

[[ 0.  3.  6.  9.]
 [ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]]


In [9]:
print(b_float.dtype)

float64


In [10]:
print(a == b_float)

[[ True False False False]
 [False False False False]
 [False False False  True]]


In [11]:
b_1d = np.arange(4, 8)
print(b_1d)

[4 5 6 7]


In [12]:
print(a < b_1d)

[[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [13]:
print(a < 6)

[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [14]:
print(a % 2)

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [15]:
print(a % 2 == 0)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [16]:
print(a < 6)

[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [17]:
print(np.count_nonzero(a < 6))

6


In [18]:
print(np.all(a < 6))

False


In [19]:
print(np.all(a < 6, axis=1))

[ True False False]


In [20]:
print(np.any(a < 6))

True


In [21]:
print(np.any(a < 6, axis=1))

[ True  True False]


In [22]:
a_nan = np.array([0, 1, np.nan])
print(a_nan)

[ 0.  1. nan]


In [23]:
print(a_nan == np.nan)

[False False False]


In [24]:
print(np.isnan(a_nan))

[False False  True]


In [25]:
print(a_nan > 0)

[False  True False]


In [26]:
x = 6

In [27]:
print(4 < x < 8)

True


In [28]:
# print(4 < a < 8)
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
print((a > 4) & (a < 8))

[[False False False False]
 [False  True  True  True]
 [False False False False]]


In [30]:
# print((a > 4) and (a < 8))
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
# print(a > 4 & a < 8)
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
x = 6
y = 6
z = 6

In [33]:
print(x == y == z)

True


In [34]:
c = np.zeros((3, 4), int)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [35]:
# print(a == b == c)
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [36]:
print((a == b) & (b == c))

[[ True False False False]
 [False False False False]
 [False False False False]]
