In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.4


In [3]:
a = np.array([[10.0, 10.1, 10.9], [-10.0, -10.1, -10.9]])
print(a)

[[ 10.   10.1  10.9]
 [-10.  -10.1 -10.9]]


In [4]:
print(np.floor(a))

[[ 10.  10.  10.]
 [-10. -11. -11.]]


In [5]:
print(np.floor(a).dtype)

float64


In [6]:
print(np.floor(a).astype(int))

[[ 10  10  10]
 [-10 -11 -11]]


In [7]:
print(np.floor(10.1))

10.0


In [8]:
print(np.trunc(a))

[[ 10.  10.  10.]
 [-10. -10. -10.]]


In [9]:
print(np.fix(a))

[[ 10.  10.  10.]
 [-10. -10. -10.]]


In [10]:
print(a.astype(int))

[[ 10  10  10]
 [-10 -10 -10]]


In [11]:
print(np.ceil(a))

[[ 10.  11.  11.]
 [-10. -10. -10.]]


In [12]:
print(np.copysign(np.ceil(np.abs(a)), a))

[[ 10.  11.  11.]
 [-10. -11. -11.]]
