In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a1 = np.ones((3, 4), int)
print(a1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
a2 = np.full((3, 4), 2)
print(a2)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [5]:
print(np.dstack([a1, a2]))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


In [6]:
print(np.dstack([a1, a2]).shape)

(3, 4, 2)


In [7]:
print(np.dstack([a1, a2])[:, :, 0])

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
print(np.dstack([a1, a2])[:, :, 1])

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [9]:
print(np.concatenate([a1.reshape(3, 4, 1), a2.reshape(3, 4, 1)], 2))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


In [10]:
a1 = np.ones(3, int)
print(a1)

[1 1 1]


In [11]:
a2 = np.full(3, 2)
print(a2)

[2 2 2]


In [12]:
print(np.dstack([a1, a2]))

[[[1 2]
  [1 2]
  [1 2]]]


In [13]:
print(np.dstack([a1, a2]).shape)

(1, 3, 2)


In [14]:
print(np.dstack([a1, a2])[:, :, 0])

[[1 1 1]]


In [15]:
print(np.dstack([a1, a2])[:, :, 1])

[[2 2 2]]


In [16]:
print(np.concatenate([a1.reshape(1, -1, 1), a2.reshape(1, -1, 1)], 2))

[[[1 2]
  [1 2]
  [1 2]]]
