In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# np.split(a, 2, 0)
# ValueError: array split does not result in an equal division

In [5]:
a0, a1 = np.array_split(a, 2, 0)

In [6]:
print(a0)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
print(a1)

[[10 11 12 13 14]]


In [8]:
a0, a1, a2 = np.array_split(a, 3, 1)

In [9]:
print(a0)

[[ 0  1]
 [ 5  6]
 [10 11]]


In [10]:
print(a1)

[[ 2  3]
 [ 7  8]
 [12 13]]


In [11]:
print(a2)

[[ 4]
 [ 9]
 [14]]
