In [1]:
import numpy as np

In [2]:
a = np.array([1, 100, 10])
print(a)

[  1 100  10]


In [3]:
print(np.argmin(a))

0


In [4]:
print(a.argmin())

0


In [5]:
a_2d = np.array([[20, 50, 30], [60, 40, 10]])
print(a_2d)

[[20 50 30]
 [60 40 10]]


In [6]:
print(np.argmin(a_2d))

5


In [7]:
print(a_2d.argmin())

5


In [8]:
print(np.argmin(a_2d, axis=0))

[0 1 1]


In [9]:
print(a_2d.argmin(axis=0))

[0 1 1]


In [10]:
print(np.min(a_2d, axis=0))

[20 40 10]


In [11]:
print(a_2d.min(axis=0))

[20 40 10]


In [12]:
print(np.argmin(a_2d, axis=1))

[0 2]


In [13]:
print(a_2d.argmin(axis=1))

[0 2]


In [14]:
print(np.min(a_2d, axis=1))

[20 10]


In [15]:
print(a_2d.min(axis=1))

[20 10]


In [16]:
idx = np.unravel_index(np.argmin(a_2d), a_2d.shape)
print(idx)

(1, 2)


In [17]:
print(a_2d[idx])

10


In [18]:
print(np.min(a_2d))

10


In [19]:
print(np.unravel_index(a_2d.argmin(), a_2d.shape))

(1, 2)
