In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
print(np.arange(3))

[0 1 2]


In [4]:
print(np.arange(3, 10))

[3 4 5 6 7 8 9]


In [5]:
print(np.arange(3, 10, 2))

[3 5 7 9]


In [6]:
print(np.arange(0.3, 1.0, 0.2))

[0.3 0.5 0.7 0.9]


In [7]:
print(np.arange(-3, 3))

[-3 -2 -1  0  1  2]


In [8]:
print(np.arange(10, 3))

[]


In [9]:
print(np.arange(10, 3, -2))

[10  8  6  4]


In [10]:
a = np.arange(3, 10)
print(a)

[3 4 5 6 7 8 9]


In [11]:
print(a.dtype)

int64


In [12]:
a_float = np.arange(3, 10, dtype=float)
print(a_float)

[3. 4. 5. 6. 7. 8. 9.]


In [13]:
print(a_float.dtype)

float64


In [14]:
print(np.arange(3, 10, 2))

[3 5 7 9]


In [15]:
print(np.arange(9, 2, -2))

[9 7 5 3]


In [16]:
print(np.arange(3, 10, 2)[::-1])

[9 7 5 3]


In [17]:
print(np.flip(np.arange(3, 10, 2)))

[9 7 5 3]


In [18]:
print(np.arange(12).reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
print(np.arange(24).reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
