In [1]:
import numpy as np

In [2]:
arr = np.array([[2, 5], [1, 3]])

In [3]:
arr_inv = np.linalg.inv(arr)
print(arr_inv)

[[ 3. -5.]
 [-1.  2.]]


In [4]:
mat = np.matrix([[2, 5], [1, 3]])

In [5]:
mat_inv = np.linalg.inv(mat)
print(mat_inv)

[[ 3. -5.]
 [-1.  2.]]


In [6]:
mat_inv = mat**-1
print(mat_inv)

[[ 3. -5.]
 [-1.  2.]]


In [7]:
mat_inv = mat.I
print(mat_inv)

[[ 3. -5.]
 [-1.  2.]]


In [8]:
result = mat * mat.I
print(result)

[[1. 0.]
 [0. 1.]]
