In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [4]:
print(np.expand_dims(a, 0))

[[[0 1 2]
  [3 4 5]]]


In [5]:
print(np.expand_dims(a, 0).shape)

(1, 2, 3)


In [6]:
print(np.expand_dims(a, 1).shape)

(2, 1, 3)


In [7]:
print(np.expand_dims(a, 2).shape)

(2, 3, 1)


In [8]:
print(np.expand_dims(a, -1).shape)

(2, 3, 1)


In [9]:
print(np.expand_dims(a, -2).shape)

(2, 1, 3)


In [10]:
print(np.expand_dims(a, -3).shape)

(1, 2, 3)


In [11]:
# print(np.expand_dims(a, 3).shape)
# AxisError: axis 3 is out of bounds for array of dimension 3

In [12]:
# print(np.expand_dims(a, -4).shape)
# AxisError: axis -4 is out of bounds for array of dimension 3

In [13]:
print(np.expand_dims(a, (0, 1, -1)).shape)

(1, 1, 2, 3, 1)


In [14]:
a_expand_dims = np.expand_dims(a, 0)

In [15]:
print(np.shares_memory(a, a_expand_dims))

True
