In [1]:
import numpy as np

In [2]:
a_nan = np.genfromtxt('data/src/sample_nan.csv', delimiter=',')
print(a_nan)

[[11. 12. nan 14.]
 [21. nan nan 24.]
 [31. 32. 33. 34.]]


In [3]:
print(np.nan == np.nan)

False


In [4]:
print(a_nan == np.nan)

[[False False False False]
 [False False False False]
 [False False False False]]


In [5]:
print(np.isnan(a_nan))

[[False False  True False]
 [False  True  True False]
 [False False False False]]


In [6]:
print(np.count_nonzero(np.isnan(a_nan)))

3


In [7]:
print(np.count_nonzero(np.isnan(a_nan), axis=0))

[0 1 2 0]


In [8]:
print(np.count_nonzero(np.isnan(a_nan), axis=1))

[1 2 0]


In [9]:
print(~np.isnan(a_nan))

[[ True  True False  True]
 [ True False False  True]
 [ True  True  True  True]]
