In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
print(np.sum(a))

66


In [5]:
print(np.sum(a, axis=0))

[12 15 18 21]


In [6]:
print(np.sum(a, axis=1))

[ 6 22 38]


In [7]:
print(np.sum(a, axis=-1))

[ 6 22 38]


In [8]:
print(np.sum(a, axis=-2))

[12 15 18 21]


In [9]:
# print(np.sum(a, axis=2))
# AxisError: axis 2 is out of bounds for array of dimension 2

In [10]:
# print(np.sum(a, axis=-3))
# AxisError: axis -3 is out of bounds for array of dimension 2

In [11]:
print(a.sum())

66


In [12]:
print(a.sum(axis=0))

[12 15 18 21]


In [13]:
print(a.sum(axis=1))

[ 6 22 38]


In [14]:
print(np.mean(a))

5.5


In [15]:
print(np.mean(a, axis=0))

[4. 5. 6. 7.]


In [16]:
print(np.mean(a, axis=1))

[1.5 5.5 9.5]


In [17]:
print(a.mean())

5.5


In [18]:
print(a.mean(axis=0))

[4. 5. 6. 7.]


In [19]:
print(a.mean(axis=1))

[1.5 5.5 9.5]


In [20]:
print(np.max(a))

11


In [21]:
print(np.max(a, axis=0))

[ 8  9 10 11]


In [22]:
print(np.max(a, axis=1))

[ 3  7 11]


In [23]:
print(np.min(a))

0


In [24]:
print(np.min(a, axis=0))

[0 1 2 3]


In [25]:
print(np.min(a, axis=1))

[0 4 8]


In [26]:
print(a.max())

11


In [27]:
print(a.max(axis=0))

[ 8  9 10 11]


In [28]:
print(a.max(axis=1))

[ 3  7 11]


In [29]:
print(a.min())

0


In [30]:
print(a.min(axis=0))

[0 1 2 3]


In [31]:
print(a.min(axis=1))

[0 4 8]
