In [1]:
import numpy as np

In [2]:
a = np.arange(10, 35).reshape(5, 5)
print(a)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [3]:
col_swap = a[:, [3, 2, 4, 0, 1]]
print(col_swap)

[[13 12 14 10 11]
 [18 17 19 15 16]
 [23 22 24 20 21]
 [28 27 29 25 26]
 [33 32 34 30 31]]


In [4]:
col_inverse = a[:, ::-1]
print(col_inverse)

[[14 13 12 11 10]
 [19 18 17 16 15]
 [24 23 22 21 20]
 [29 28 27 26 25]
 [34 33 32 31 30]]


In [5]:
col_select = a[:, [2, 4, 0]]
print(col_select)

[[12 14 10]
 [17 19 15]
 [22 24 20]
 [27 29 25]
 [32 34 30]]


In [6]:
col_select2 = a[:, [2, 2, 2]]
print(col_select2)

[[12 12 12]
 [17 17 17]
 [22 22 22]
 [27 27 27]
 [32 32 32]]


In [7]:
row_swap = a[[3, 2, 4, 0, 1], :]
print(row_swap)

[[25 26 27 28 29]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
row_swap = a[[3, 2, 4, 0, 1]]
print(row_swap)

[[25 26 27 28 29]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [9]:
row_inverse = a[::-1]
print(row_inverse)

[[30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]]


In [10]:
row_select = a[[2, 4, 0]]
print(row_select)

[[20 21 22 23 24]
 [30 31 32 33 34]
 [10 11 12 13 14]]


In [11]:
row_select2 = a[[2, 2, 2]]
print(row_select2)

[[20 21 22 23 24]
 [20 21 22 23 24]
 [20 21 22 23 24]]
