In [1]:
import numpy as np

In [2]:
a1 = np.ones((3, 4), int)
print(a1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [3]:
a2 = np.full((3, 4), 2)
print(a2)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [4]:
print(np.dstack([a1, a2]))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


In [5]:
print(np.dstack([a1, a2]).shape)

(3, 4, 2)


In [6]:
print(np.concatenate([a1.reshape(3, 4, 1), a2.reshape(3, 4, 1)], 2))

[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]


In [7]:
a1 = np.ones(3, int)
print(a1)

[1 1 1]


In [8]:
a2 = np.full(3, 2)
print(a2)

[2 2 2]


In [9]:
print(np.dstack([a1, a2]))

[[[1 2]
  [1 2]
  [1 2]]]


In [10]:
print(np.dstack([a1, a2]).shape)

(1, 3, 2)
