In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a_int64 = np.arange(3)
print(a_int64)

[0 1 2]


In [4]:
print(a_int64.dtype)

int64


In [5]:
a_float64 = np.arange(6).reshape(2, 3) / 10
print(a_float64)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]]


In [6]:
print(a_float64.dtype)

float64


In [7]:
print(np.zeros_like(a_int64))

[0 0 0]


In [8]:
print(np.zeros_like(a_int64).dtype)

int64


In [9]:
print(np.zeros_like(a_float64))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.zeros_like(a_float64).dtype)

float64


In [11]:
print(np.zeros_like(a_int64, dtype=np.float64))

[0. 0. 0.]


In [12]:
print(np.zeros_like(a_int64, dtype=np.float64).dtype)

float64


In [13]:
print(np.ones_like(a_int64))

[1 1 1]


In [14]:
print(np.ones_like(a_int64).dtype)

int64


In [15]:
print(np.ones_like(a_float64))

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
print(np.ones_like(a_float64).dtype)

float64


In [17]:
print(np.ones_like(a_int64, dtype=np.float64))

[1. 1. 1.]


In [18]:
print(np.ones_like(a_int64, dtype=np.float64).dtype)

float64


In [19]:
print(np.full_like(a_int64, 100))

[100 100 100]


In [20]:
print(np.full_like(a_int64, 100).dtype)

int64


In [21]:
print(np.full_like(a_float64, 100))

[[100. 100. 100.]
 [100. 100. 100.]]


In [22]:
print(np.full_like(a_float64, 100).dtype)

float64


In [23]:
print(np.full_like(a_int64, 0.123))

[0 0 0]


In [24]:
print(np.full_like(a_int64, 0.123).dtype)

int64


In [25]:
print(np.full_like(a_int64, 0.123, dtype=np.float64))

[0.123 0.123 0.123]


In [26]:
print(np.full_like(a_int64, 0.123, dtype=np.float64).dtype)

float64
