In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(16).reshape(4, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a0, a1 = np.vsplit(a, 2)

In [5]:
print(a0)

[[0 1 2 3]
 [4 5 6 7]]


In [6]:
print(a1)

[[ 8  9 10 11]
 [12 13 14 15]]


In [7]:
a0, a1 = np.split(a, [1])

In [8]:
print(a0)

[[0 1 2 3]]


In [9]:
print(a1)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
