In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(6).reshape(2, 3)
print(a)

[[0 1 2]
 [3 4 5]]


In [4]:
b = np.zeros_like(a)
print(b)

[[0 0 0]
 [0 0 0]]


In [5]:
print(a)

[[0 1 2]
 [3 4 5]]


In [6]:
a[:, :] = 0
print(a)

[[0 0 0]
 [0 0 0]]


In [7]:
a[:] = 1
print(a)

[[1 1 1]
 [1 1 1]]


In [8]:
print(a.dtype)

int64


In [9]:
a[:] = 0.123
print(a)

[[0 0 0]
 [0 0 0]]


In [10]:
a = a.astype(np.float64)
a[:] = 0.123
print(a)

[[0.123 0.123 0.123]
 [0.123 0.123 0.123]]
