In [1]:
import numpy as np

In [2]:
print(np.tri(4))

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [3]:
print(type(np.tri(4)))

<class 'numpy.ndarray'>


In [4]:
print(np.tri(4).dtype)

float64


In [5]:
print(np.tri(4, dtype=int))

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


In [6]:
print(np.tri(4, dtype=int).dtype)

int64


In [7]:
print(np.tri(4, k=1))

[[1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
print(np.tri(4, k=-1))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]]


In [9]:
print(np.tri(3, 4))

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]]


In [10]:
print(np.tri(3, 4, k=-1))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]]


In [11]:
print(np.tri(4).T)

[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]


In [12]:
print(np.tri(3, 4).T)

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [13]:
print(np.tri(4, k=1).T)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]]


In [14]:
print(np.tri(4, k=-1).T)

[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
