In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)
print(a.dtype)

[1 2 3]
int64


In [3]:
print((a / 1).dtype)

float64


In [4]:
print((a / 1.0).dtype)

float64


In [5]:
print((a + 1).dtype)

int64


In [6]:
print((a + 1.0).dtype)

float64


In [7]:
print((a - 1).dtype)

int64


In [8]:
print((a - 1.0).dtype)

float64


In [9]:
print((a * 1).dtype)

int64


In [10]:
print((a * 1.0).dtype)

float64


In [11]:
print((a // 1).dtype)

int64


In [12]:
print((a // 1.0).dtype)

float64


In [13]:
print((a ** 1).dtype)

int64


In [14]:
print((a ** 1.0).dtype)

float64


In [15]:
ones_int16 = np.ones(3, np.int16)
print(ones_int16)

[1 1 1]


In [16]:
ones_int32 = np.ones(3, np.int32)
print(ones_int32)

[1 1 1]


In [17]:
print((ones_int16 + ones_int32).dtype)

int32


In [18]:
ones_float16 = np.ones(3, np.float16)
print(ones_float16)

[1. 1. 1.]


In [19]:
print((ones_int16 + ones_float16).dtype)

float32


In [20]:
ones_int16[0] = 10.9
print(ones_int16)

[10  1  1]


In [21]:
print(ones_int16.dtype)

int16
