In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(np.clip(a, 2, 7))

[2 2 2 3 4 5 6 7 7 7]


In [5]:
print(np.clip(a, None, 7))

[0 1 2 3 4 5 6 7 7 7]


In [6]:
print(np.clip(a, 2, None))

[2 2 2 3 4 5 6 7 8 9]


In [7]:
# print(np.clip(a, 2))
# TypeError: clip() missing 1 required positional argument: 'a_max'

In [8]:
print(np.clip(a, 7, 2))

[2 2 2 2 2 2 2 2 2 2]


In [9]:
a_clip = np.clip(a, 2, 7)
print(a_clip)

[2 2 2 3 4 5 6 7 7 7]


In [10]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
print(np.clip(l, 2, 7))

[2 2 2 3 4 5 6 7 7 7]


In [13]:
print(type(np.clip(l, 2, 7)))

<class 'numpy.ndarray'>


In [14]:
print(a.clip(2, 7))

[2 2 2 3 4 5 6 7 7 7]


In [15]:
print(a.clip(None, 7))

[0 1 2 3 4 5 6 7 7 7]


In [16]:
print(a.clip(2, None))

[2 2 2 3 4 5 6 7 8 9]


In [17]:
print(a.clip(2))

[2 2 2 3 4 5 6 7 8 9]


In [18]:
print(a.clip(min=2))

[2 2 2 3 4 5 6 7 8 9]


In [19]:
print(a.clip(max=7))

[0 1 2 3 4 5 6 7 7 7]


In [20]:
print(a.clip(7, 2))

[2 2 2 2 2 2 2 2 2 2]


In [21]:
a_clip = a.clip(2, 7)
print(a_clip)

[2 2 2 3 4 5 6 7 7 7]


In [22]:
print(a)

[0 1 2 3 4 5 6 7 8 9]
