In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print(a < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [5]:
print(np.where(a < 4, -1, 100))

[[ -1  -1  -1]
 [ -1 100 100]
 [100 100 100]]


In [6]:
print(np.where([True, False, True], -1, 100))

[ -1 100  -1]


In [7]:
print(np.where([-2, -1, 0, 1, 2], -1, 100))

[ -1  -1 100  -1  -1]


In [8]:
print((a > 2) & (a < 6))

[[False False False]
 [ True  True  True]
 [False False False]]


In [9]:
print(np.where((a > 2) & (a < 6), -1, 100))

[[100 100 100]
 [ -1  -1  -1]
 [100 100 100]]


In [10]:
print((a > 2) & (a < 6) | (a == 7))

[[False False False]
 [ True  True  True]
 [False  True False]]


In [11]:
print(np.where((a > 2) & (a < 6) | (a == 7), -1, 100))

[[100 100 100]
 [ -1  -1  -1]
 [100  -1 100]]


In [12]:
print(np.where(a < 4, -1, a))

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [13]:
print(np.where(a < 4, a, 100))

[[  0   1   2]
 [  3 100 100]
 [100 100 100]]


In [14]:
a_org = np.arange(9).reshape(3, 3)
print(a_org)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
a_new = np.where(a_org < 4, -1, a_org)
print(a_new)

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [16]:
print(a_org)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
a_org[a_org < 4] = -1
print(a_org)

[[-1 -1 -1]
 [-1  4  5]
 [ 6  7  8]]


In [18]:
print(np.where(a < 4, a * 10, a + 100))

[[  0  10  20]
 [ 30 104 105]
 [106 107 108]]


In [19]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print(a.sum(axis=0, keepdims=True))

[[12 15 18 21]]


In [21]:
print(np.where(a < 6, a.sum(axis=0, keepdims=True), 0))

[[12 15 18 21]
 [12 15  0  0]
 [ 0  0  0  0]]


In [22]:
print(a.sum(axis=1, keepdims=True))

[[ 6]
 [22]
 [38]]


In [23]:
print(np.where(a < 6, a.sum(axis=1, keepdims=True), 0))

[[ 6  6  6  6]
 [22 22  0  0]
 [ 0  0  0  0]]


In [24]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
print(np.where(a < 4))

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))


In [26]:
print(type(np.where(a < 4)))

<class 'tuple'>


In [27]:
print(type(np.where(a < 4)[0]))

<class 'numpy.ndarray'>


In [28]:
print(np.nonzero(a < 4))

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))


In [29]:
print(list(zip(*np.where(a < 4))))

[(0, 0), (0, 1), (0, 2), (1, 0)]


In [30]:
print(np.argwhere(a < 4))

[[0 0]
 [0 1]
 [0 2]
 [1 0]]


In [31]:
a_3d = np.arange(24).reshape(2, 3, 4)
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
print(a_3d % 5 == 0)

[[[ True False False False]
  [False  True False False]
  [False False  True False]]

 [[False False False  True]
  [False False False False]
  [ True False False False]]]


In [33]:
print(np.where(a_3d % 5 == 0))

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 2]), array([0, 1, 2, 3, 0]))


In [34]:
print(np.nonzero(a_3d % 5 == 0))

(array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 2]), array([0, 1, 2, 3, 0]))


In [35]:
print(list(zip(*np.where(a_3d % 5 == 0))))

[(0, 0, 0), (0, 1, 1), (0, 2, 2), (1, 0, 3), (1, 2, 0)]


In [36]:
print(np.argwhere(a_3d % 5 == 0))

[[0 0 0]
 [0 1 1]
 [0 2 2]
 [1 0 3]
 [1 2 0]]


In [37]:
a_1d = np.arange(6)
print(a_1d)

[0 1 2 3 4 5]


In [38]:
print(np.where(a_1d < 3))

(array([0, 1, 2]),)


In [39]:
print(np.nonzero(a_1d < 3))

(array([0, 1, 2]),)


In [40]:
print(list(zip(*np.where(a_1d < 3))))

[(0,), (1,), (2,)]


In [41]:
print(np.argwhere(a_1d < 3))

[[0]
 [1]
 [2]]
