In [1]:
import numpy as np

In [2]:
a1 = np.arange(5)
print(a1)

[0 1 2 3 4]


In [3]:
a2 = np.arange(5, 10)
print(a2)

[5 6 7 8 9]


In [4]:
np.savez_compressed('data/temp/np_savez_comp', a1, a2)

In [5]:
print(type(np.load('data/temp/np_savez_comp.npz')))

<class 'numpy.lib.npyio.NpzFile'>


In [6]:
npz_comp = np.load('data/temp/np_savez_comp.npz')

In [7]:
print(npz_comp.files)

['arr_0', 'arr_1']


In [8]:
print(npz_comp['arr_0'])

[0 1 2 3 4]


In [9]:
print(npz_comp['arr_1'])

[5 6 7 8 9]


In [10]:
np.savez_compressed('data/temp/np_savez_comp_kw', x=a1, y=a2)

In [11]:
npz_comp_kw = np.load('data/temp/np_savez_comp_kw.npz')

In [12]:
print(npz_comp_kw.files)

['x', 'y']


In [13]:
print(npz_comp_kw['x'])

[0 1 2 3 4]


In [14]:
print(npz_comp_kw['y'])

[5 6 7 8 9]
