In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.0


In [3]:
a_1d = np.array([1, 2, 3, 4, 5, 6])
print(a_1d)

[1 2 3 4 5 6]


In [4]:
print(np.cumsum(a_1d))

[ 1  3  6 10 15 21]


In [5]:
print(np.cumsum(a_1d, dtype=float))

[ 1.  3.  6. 10. 15. 21.]


In [6]:
print(a_1d.cumsum())

[ 1  3  6 10 15 21]


In [7]:
print(np.cumprod(a_1d))

[  1   2   6  24 120 720]


In [8]:
print(np.cumprod(a_1d, dtype=float))

[  1.   2.   6.  24. 120. 720.]


In [9]:
print(a_1d.cumprod())

[  1   2   6  24 120 720]


In [10]:
l = [1, 2, 3, 4, 5, 6]

In [11]:
print(np.cumsum(l))

[ 1  3  6 10 15 21]


In [12]:
print(type(np.cumsum(l)))

<class 'numpy.ndarray'>


In [13]:
a_2d = a_1d.reshape(2, 3)
print(a_2d)

[[1 2 3]
 [4 5 6]]


In [14]:
print(np.cumsum(a_2d))

[ 1  3  6 10 15 21]


In [15]:
print(np.cumsum(a_2d, axis=0))

[[1 2 3]
 [5 7 9]]


In [16]:
print(np.cumsum(a_2d, axis=1))

[[ 1  3  6]
 [ 4  9 15]]


In [17]:
print(np.cumprod(a_2d))

[  1   2   6  24 120 720]


In [18]:
print(np.cumprod(a_2d, axis=0))

[[ 1  2  3]
 [ 4 10 18]]


In [19]:
print(np.cumprod(a_2d, axis=1))

[[  1   2   6]
 [  4  20 120]]
