In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.2


In [3]:
print(np.abs)

<ufunc 'absolute'>


In [4]:
print(np.abs is np.absolute)

True


In [5]:
a = np.array([-2, -1, 0, 1, 2])

In [6]:
print(np.abs(a))

[2 1 0 1 2]


In [7]:
print(type(np.abs(a)))

<class 'numpy.ndarray'>


In [8]:
l = [-2, -1, 0, 1, 2]

In [9]:
print(np.abs(l))

[2 1 0 1 2]


In [10]:
print(type(np.abs(l)))

<class 'numpy.ndarray'>


In [11]:
print(np.abs(-100))

100


In [12]:
print(type(np.abs(-100)))

<class 'numpy.int64'>


In [13]:
a_int = np.array([-2, -1, 0, 1, 2])

In [14]:
print(a_int.dtype)

int64


In [15]:
print(np.abs(a_int))

[2 1 0 1 2]


In [16]:
print(np.abs(a_int).dtype)

int64


In [17]:
a_float = np.array([-2.0, -1.0, 0, 1.0, 2.0])

In [18]:
print(a_float.dtype)

float64


In [19]:
print(np.abs(a_float))

[2. 1. 0. 1. 2.]


In [20]:
print(np.abs(a_float).dtype)

float64


In [21]:
a_complex = np.array([3 + 4j, 5 + 12j])

In [22]:
print(a_complex.dtype)

complex128


In [23]:
print(np.abs(a_complex))

[ 5. 13.]


In [24]:
print(np.abs(a_complex).dtype)

float64


In [25]:
a = np.array([-2, -1, 0, 1, 2])

In [26]:
print(a.__abs__())

[2 1 0 1 2]


In [27]:
print(abs(a))

[2 1 0 1 2]


In [28]:
print(type(abs(a)))

<class 'numpy.ndarray'>


In [29]:
a_complex = np.array([3 + 4j, 5 + 12j])

In [30]:
print(abs(a_complex))

[ 5. 13.]


In [31]:
a_int = np.array([-2, -1, 0, 1, 2])

In [32]:
print(a_int.dtype)

int64


In [33]:
print(np.fabs(a_int))

[2. 1. 0. 1. 2.]


In [34]:
print(np.fabs(a_int).dtype)

float64


In [35]:
a_complex = np.array([3 + 4j, 5 + 12j])

In [36]:
# print(np.fabs(a_complex))
# TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''