In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.1


In [3]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
%%timeit
a.ravel()

43.6 ns ± 0.298 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [5]:
%%timeit
a.flatten()

249 ns ± 0.971 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
%%timeit
a.reshape(-1)

80.2 ns ± 0.145 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [7]:
a_large = np.arange(1000000).reshape(100, 100, 100)

In [8]:
%%timeit
a_large.ravel()

43.6 ns ± 0.118 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [9]:
%%timeit
a_large.flatten()

423 µs ± 25.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
%%timeit
a_large.reshape(-1)

80 ns ± 0.0587 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
