In [1]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.1.4


In [3]:
print(np.__version__)

1.26.2


In [4]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [5]:
df = pd.DataFrame(a)
print(df)

   0  1  2
0  0  1  2
1  3  4  5


In [6]:
print(np.shares_memory(a, df))

True


In [7]:
print(df._is_view)

True


In [8]:
a[0, 0] = 100
print(a)

[[100   1   2]
 [  3   4   5]]


In [9]:
print(df)

     0  1  2
0  100  1  2
1    3  4  5


In [10]:
a_str = np.array([['a', 'b', 'c'], ['x', 'y', 'z']])
print(a_str)

[['a' 'b' 'c']
 ['x' 'y' 'z']]


In [11]:
df_str = pd.DataFrame(a_str)
print(df_str)

   0  1  2
0  a  b  c
1  x  y  z


In [12]:
print(np.shares_memory(a_str, df_str))

False


In [13]:
print(df_str._is_view)

False


In [14]:
a_str[0, 0] = 'A'
print(a_str)

[['A' 'b' 'c']
 ['x' 'y' 'z']]


In [15]:
print(df_str)

   0  1  2
0  a  b  c
1  x  y  z


In [16]:
df_homo = pd.DataFrame([[0, 1, 2], [3, 4, 5]])
print(df_homo)

   0  1  2
0  0  1  2
1  3  4  5


In [17]:
print(df_homo.dtypes)

0    int64
1    int64
2    int64
dtype: object


In [18]:
a_homo = df_homo.values
print(a_homo)

[[0 1 2]
 [3 4 5]]


In [19]:
print(np.shares_memory(a_homo, df_homo))

True


In [20]:
df_homo.iat[0, 0] = 100
print(df_homo)

     0  1  2
0  100  1  2
1    3  4  5


In [21]:
print(a_homo)

[[100   1   2]
 [  3   4   5]]


In [22]:
df_hetero = pd.DataFrame([[0, 'x'], [1, 'y']])
print(df_hetero)

   0  1
0  0  x
1  1  y


In [23]:
print(df_hetero.dtypes)

0     int64
1    object
dtype: object


In [24]:
a_hetero = df_hetero.values
print(a_hetero)

[[0 'x']
 [1 'y']]


In [25]:
print(np.shares_memory(a_hetero, df_hetero))

False


In [26]:
df_hetero.iat[0, 0] = 100
print(df_hetero)

     0  1
0  100  x
1    1  y


In [27]:
print(a_hetero)

[[0 'x']
 [1 'y']]
