In [1]:
import pandas as pd
import numpy as np

In [2]:
print(pd.__version__)

2.1.4


In [3]:
print(np.__version__)

1.26.2


In [4]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=['X', 'Y'])
print(df)

   A  B
X  1  3
Y  2  4


In [5]:
print(df.to_numpy())

[[1 3]
 [2 4]]


In [6]:
print(type(df.to_numpy()))

<class 'numpy.ndarray'>


In [7]:
s = df['A']
print(s)

X    1
Y    2
Name: A, dtype: int64


In [8]:
print(s.to_numpy())

[1 2]


In [9]:
print(type(s.to_numpy()))

<class 'numpy.ndarray'>


In [10]:
df_int = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=['X', 'Y'])
print(df_int)

   A  B
X  1  3
Y  2  4


In [11]:
print(df_int.dtypes)

A    int64
B    int64
dtype: object


In [12]:
print(df_int.to_numpy())

[[1 3]
 [2 4]]


In [13]:
print(df_int.to_numpy().dtype)

int64


In [14]:
df_int_float = pd.DataFrame({'A': [1, 2], 'B': [0.1, 0.2]}, index=['X', 'Y'])
print(df_int_float)

   A    B
X  1  0.1
Y  2  0.2


In [15]:
print(df_int_float.dtypes)

A      int64
B    float64
dtype: object


In [16]:
print(df_int_float.to_numpy())

[[1.  0.1]
 [2.  0.2]]


In [17]:
print(df_int_float.to_numpy().dtype)

float64


In [18]:
df_int_str = pd.DataFrame({'A': [1, 2], 'B': ['abc', 'xyz']}, index=['X', 'Y'])
print(df_int_str)

   A    B
X  1  abc
Y  2  xyz


In [19]:
print(df_int_str.dtypes)

A     int64
B    object
dtype: object


In [20]:
print(df_int_str.to_numpy())

[[1 'abc']
 [2 'xyz']]


In [21]:
print(df_int_str.to_numpy().dtype)

object


In [22]:
print(df_int_str.to_numpy()[0, 0])

1


In [23]:
print(type(df_int_str.to_numpy()[0, 0]))

<class 'int'>


In [24]:
print(df_int_str.to_numpy()[0, 1])

abc


In [25]:
print(type(df_int_str.to_numpy()[0, 1]))

<class 'str'>


In [26]:
print(df_int_float.to_numpy(dtype='float32'))

[[1.  0.1]
 [2.  0.2]]


In [27]:
print(df_int_float.to_numpy(dtype=int))

[[1 0]
 [2 0]]


In [28]:
# print(df_int_str.to_numpy(dtype=int))
# ValueError: invalid literal for int() with base 10: 'abc'

In [29]:
df_int_float_str = pd.DataFrame({'A': [1, 2], 'B': [0.1, 0.2], 'C': ['abc', 'xyz']}, index=['X', 'Y'])
print(df_int_float_str)

   A    B    C
X  1  0.1  abc
Y  2  0.2  xyz


In [30]:
print(df_int_float_str.select_dtypes('number').to_numpy())

[[1.  0.1]
 [2.  0.2]]


In [31]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=['X', 'Y'])
a = df.to_numpy()

In [32]:
print(np.shares_memory(df, a))

True


In [33]:
a[0, 0] = 100
print(a)

[[100   3]
 [  2   4]]


In [34]:
print(df)

     A  B
X  100  3
Y    2  4


In [35]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=['X', 'Y'])
a_copy = df.to_numpy(copy=True)

In [36]:
print(np.shares_memory(df, a_copy))

False


In [37]:
a_copy[0, 0] = 100
print(a_copy)

[[100   3]
 [  2   4]]


In [38]:
print(df)

   A  B
X  1  3
Y  2  4


In [39]:
df_int_float = pd.DataFrame({'A': [1, 2], 'B': [0.1, 0.2]}, index=['X', 'Y'])
a_float = df_int_float.to_numpy()

In [40]:
print(np.shares_memory(df_int_float, a_float))

False


In [41]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=['X', 'Y'])
print(df)

   A  B
X  1  3
Y  2  4


In [42]:
print(df.values)

[[1 3]
 [2 4]]


In [43]:
print(type(df.values))

<class 'numpy.ndarray'>


In [44]:
s = df['A']
print(s)

X    1
Y    2
Name: A, dtype: int64


In [45]:
print(s.values)

[1 2]


In [46]:
print(type(s.values))

<class 'numpy.ndarray'>


In [47]:
df_int_float = pd.DataFrame({'A': [1, 2], 'B': [0.1, 0.2]}, index=['X', 'Y'])
print(df_int_float.values)

[[1.  0.1]
 [2.  0.2]]


In [48]:
print(df_int_float.values.dtype)

float64


In [49]:
df_int_str = pd.DataFrame({'A': [1, 2], 'B': ['abc', 'xyz']}, index=['X', 'Y'])
print(df_int_str.values)

[[1 'abc']
 [2 'xyz']]


In [50]:
print(df_int_str.values.dtype)

object


In [51]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]}, index=['X', 'Y'])
print(np.shares_memory(df, df.values))

True


In [52]:
df_int_float = pd.DataFrame({'A': [1, 2], 'B': [0.1, 0.2]}, index=['X', 'Y'])
print(np.shares_memory(df_int_float, df_int_float.values))

False


In [53]:
print(np.shares_memory(df, df.values.copy()))

False
