In [1]:
import pandas as pd

In [2]:
print(pd)

<module 'pandas' from '/usr/local/lib/python3.7/site-packages/pandas/__init__.py'>


In [3]:
print(pd.np)

<module 'numpy' from '/usr/local/lib/python3.7/site-packages/numpy/__init__.py'>


In [4]:
import numpy as np

In [5]:
print(pd.np is np)

True


In [6]:
print(pd.np.mean is np.mean)

True


In [7]:
a = pd.np.arange(12).reshape(3, 4)

In [8]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(pd.np.pi)

3.141592653589793


In [11]:
print(pd.np.e)

2.718281828459045
