In [1]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, lil_matrix, save_npz, load_npz

In [2]:
l = [[0, 1, 2],
     [3, 0, 4],
     [0, 0, 0]]

In [3]:
csr = csr_matrix(l)
csc = csc_matrix(l)

In [4]:
save_npz('data/temp/csr.npz', csr)
save_npz('data/temp/csc.npz', csc)

In [5]:
csr_ = load_npz('data/temp/csr.npz')
print(csr_.toarray())

[[0 1 2]
 [3 0 4]
 [0 0 0]]


In [6]:
print(type(csr))

<class 'scipy.sparse.csr.csr_matrix'>


In [7]:
csc_ = load_npz('data/temp/csc.npz')
print(csc_.toarray())

[[0 1 2]
 [3 0 4]
 [0 0 0]]


In [8]:
print(type(csc))

<class 'scipy.sparse.csc.csc_matrix'>


In [9]:
lil = lil_matrix(l)

In [10]:
# save_npz('data/temp/lil.npz', lil)
# NotImplementedError: Save is not implemented for sparse matrix of format lil.

In [11]:
npz = np.load('data/temp/csr.npz')

In [12]:
print(npz.files)

['indices', 'indptr', 'format', 'shape', 'data']


In [13]:
print(npz['data'])

[1 2 3 4]


In [14]:
print(npz['indices'])

[1 2 0 2]


In [15]:
print(npz['indptr'])

[0 2 4 4]


In [16]:
print(npz['format'])

b'csr'


In [17]:
print(npz['shape'])

[3 3]
