In [1]:
import sklearn  # Required only for version check

In [2]:
print(sklearn.__version__)

1.3.2


In [3]:
from sklearn import preprocessing

In [4]:
l_1d = [0, 1, 2, 3, 4]
l_2d = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [5]:
mm = preprocessing.MinMaxScaler()

In [6]:
# mm.fit_transform(l_1d)
# ValueError: Expected 2D array, got 1D array instead:

In [7]:
print(mm.fit_transform(l_2d))

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [8]:
print(type(mm.fit_transform(l_2d)))

<class 'numpy.ndarray'>


In [9]:
print(preprocessing.minmax_scale(l_1d))

[0.   0.25 0.5  0.75 1.  ]


In [10]:
print(preprocessing.minmax_scale(l_2d))

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [11]:
print(preprocessing.minmax_scale(l_2d, axis=1))

[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


In [12]:
# print(preprocessing.minmax_scale(l_2d, axis=None))
# InvalidParameterError: The 'axis' parameter of minmax_scale must be a int among {0, 1}. Got None instead.

In [13]:
ss = preprocessing.StandardScaler()

In [14]:
print(ss.fit_transform(l_2d))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [15]:
print(type(ss.fit_transform(l_2d)))

<class 'numpy.ndarray'>


In [16]:
print(preprocessing.scale(l_1d))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
print(preprocessing.scale(l_2d))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [18]:
print(preprocessing.scale(l_2d, axis=1))

[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]
